/*
 * Athletic Assistant XR — Data Fetcher
 * Parses the CSV log file generated by the C fitness engine.
 */

import fs from 'fs';
import path from 'path';
import { SessionRecord } from '../types';

const LOG_PATH = path.resolve(process.cwd(), '../logs/fitness_sessions.log');

export async function getFitnessData(): Promise<SessionRecord[]> {
  try {
    if (!fs.existsSync(LOG_PATH)) {
      console.warn('Fitness log not found at:', LOG_PATH);
      return [];
    }

    const fileContent = fs.readFileSync(LOG_PATH, 'utf-8');
    const lines = fileContent.trim().split('\n');

    // Skip CSV header
    const dataLines = lines.slice(1);

    return dataLines.map((line) => {
      const [
        timestamp,
        userName,
        bmi,
        bmr,
        staminaScore,
        recommendedCalories,
        xrMode
      ] = line.split(',');

      return {
        timestamp,
        userName,
        bmi: parseFloat(bmi),
        bmr: parseFloat(bmr),
        staminaScore: parseFloat(staminaScore),
        recommendedCalories: parseFloat(recommendedCalories),
        xrMode: xrMode?.trim() || 'CLI'
      };
    });
  } catch (error) {
    console.error('Error parsing fitness log:', error);
    return [];
  }
}
